// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int mumber = Integer.parseInt(args[0]);
		int greaterNumber = 0;
		int smallerNumber = 0;
		
		for (int i = 1; i<=mumber; i++) {
			double randomNumner = Math.random();
			if (randomNumner>0.5){
				greaterNumber++;
			}
			else{
				smallerNumber++;
			}
	}
	System.out.println("> 0.5: " + smallerNumber+" times");
	System.out.println("<= 0.5: " + greaterNumber+" times");
	if(smallerNumber!= 0 && greaterNumber!= 0){
			float ratio = (float)smallerNumber/ greaterNumber;
			System.out.println("Ratio: " + ratio);
		}

  }
}
